### ISSUE TITLE
GCC 9.3 is not supported compiler in latest version

### ISSUE THREAD

**Issue by wedhusgembel** [deu/palemoon-overlay#106]
Hi,
after #88 GCC 9.3 has been supported version. Why remove it in latest version #104 #103 ?

**Comment by CaseOf** [comment]
Hello,
It is not supported because build with GCC 9 fails.

**Comment by wedhusgembel** [comment]
GCC 9 is in stable keyword right? if package cant be built with stable build time dependency why not mark it as ~ (testing) ?

**Comment by eslafgh** [comment]
The errors that prevent 29.0.1 compiling with gcc 9.3 are format-overflow warnings that are treated as errors (-Werror=format) while compiling o/js/src/jit/Unified_cpp_js_src_jit14.cpp.

From the release notes - 29 enables "inlining of code optimization in our JIT compiler", the format-overflow errors involve a chain on inline functions so I assume 28.17 was OK because the inlining was off.

As a work around I did get 29.0.1 to compile with gcc 9.3, by overriding the compiler check and adding -Wformat-overflow to the compiler flags using package.env, i.e for me setting CFLAGS, CXXFAGS etc to "-O2 -march=native -pipe -Wformat-overflow".
This turns the errors back into warnings. Checking the build.log at the end I had 3 format-overflow warnings, the two that were causing the problem and the other which would not be an error because of MoonchildProductions/UXP@b51ff1f69273f116eb9a1a36043e23d77d2235cb.

**Comment by CaseOf** [comment]
I wanted to get Tobin opinion on this issue. He just told me on IRC:

> [2021-02-21T16:40:41+00:00] <@MobileTobin> I think this had already been fixed and a specific or targeted solution is superior over some bungling inept global flag override

**Comment by CaseOf** [comment]
You can disable these flags customisations with 29.1.0.
