### ISSUE TITLE
Uploading your palemoon ebuild to official gentoo repository

### ISSUE THREAD

**Issue by Sharrisii** [deu/palemoon-overlay#63]
Hi deu,

Take a look at https://github.com/Sharrisii/gentoo/tree/master/www-client/palemoon
If you agree that I would upload your ebuild to the gentoo repo, please let me know and also tell me under which license that would need to be done.
I added in a link to your repo as the upstream source. Tell me if anything else needs to be changed on it.

**Comment by deu** [comment]
There are several things wrong with it:

- You have added an ebuild for an outdated version of Pale Moon. 27.9.0 is out and so is the ebuild for it.
- You have ignored the USE flag descriptions in the `metadata.xml` and supplied your own `metadata.xml` which has no mention of them. Also the `upstream` tag isn't supposed to be used like that, but it should point to the **_project_**'s upstream, i.e. `MoonchildProductions/Pale-Moon`.
- You have not added the `palemoon-4` eclass required by the ebuild. Without it, the ebuild wouldn't work.
- You have not added the `files` directory. Again, without it the ebuild wouldn't work.

In fact you do have an empty `Manifest` file, in case you hadn't noticed. I assume it was created by a failed `ebuild` run.

What are you trying to do here? Submit a pull request to [gentoo/gentoo](https://github.com/gentoo/gentoo) in my stead? I would really prefer you not to do that at this time. There are reasons I haven't done so myself.
The main reason is that Pale Moon can't be built with the default gcc. Even worse, the required gcc version is masked. This is going to change with Pale Moon 28, so it could be maybe reconsidered then.
Additionally the ebuilds would need specific changes before I would submit them, since the way I do some stuff is due to them being inside a third-party overlay.

So I'm sorry to say that no, I don't want this to happen.
