### ISSUE TITLE
Feature requests for v28

### ISSUE THREAD

**Issue by Sharrisii** [deu/palemoon-overlay#64]
Hey deu,

Sorry for issue 63; I didn't mean to do a pull request to gentoo/gentoo and take credits before you could; rather I just thought you were not going to do a pull request to gentoo/gentoo at all, and so I thought I'd do it (also didn't know about the gcc problem when I wrote the github issue to you).
Anyway, I'll leave you to it, but I have a few requests when you upload palemoon v28 to the gentoo repo. Could you:
* make webrtc an option (so can be disabled if preferred)
* make speech an option (so can be disabled if preferred)
* system-cairo, system-pixman (so can be disabled if preferred)
* system-spell, wave spell (so can be disabled if preferred)

Also, the following should be optional (but given that's already the case for 27.9.1, that's probably also already going to be the case for 28 too):
* pulseaudio / alsa
* gtk 2 /gtk 3
* cpu_flags_x86_sse / cpu_flags_x86_sse2
* devtools

In addition, perhaps integrate the ability to allow selecting between building with glibc and building with musl. I proposed this before (at https://github.com/Bfgeshka/octopus/issues/10 ), but we're now actually working on it, so perhaps that we can have something ready when v28 (or v28.1) becomes available so you can easily add it to the ebuild.

**Comment by SpockMan02** [comment]
Making all of those changes isn't allowed if you want to call the result Pale Moon.

8. b. "When redistributing the browser in source form through a distribution system that imposes or can impose a specific configuration for building and run-time operation (e.g. portage ebuilds, ABS/AUR PKGBUILDs, port Makefiles) that configures the build system to use official branding in the resulting binary, you (as a package maintainer/distributor) must adhere as closely as possible to the build configuration used in official generic binaries. You must not reconfigure the build system or browser preferences beyond what is necessary to produce the browser on the target operating system. Any individual additional configurations done on the browser (either build- or run-time) must be done by the end user, not imposed by package maintainers/distributors. In principle, browser preferences and the supplied profile defaults must not be changed for the exception outlined in this point."

It's not the end of the world, though: The solution is to rebrand the browser; you can do whatever you like with a fork as long as it doesn't infringe on Moonchild Productions trademarks (basically because if you make a bunch of changes and something goes wrong, it shouldn't be associated with the Pale Moon name and brand).

Hopefully, what happened with the OpenBSD port will not be repeated.

**Comment by Sharrisii** [comment]
@SpockMan02 and @mattatobin : official branding is already a option in the deu build and with TAZ, palemoon would be build with official branding= off. I already asked permission to Moonchild back in january 2018 (see https://forum.palemoon.org/viewtopic.php?f=37&t=17621&p=132098 ). I also discussed it with moonchild directly (not just in forum posts). If there are additional things I should do, let me know.

**Comment by mattatobin** [comment]
Yeah well these "suggestions" won't be done here.

**Comment by Sharrisii** [comment]
Oh, you mean I proposed to make certain things optional which violate the terms of the Redistribution License somehow ? If so, which ones violate the terms and can't be included, and the ones that violate the terms, at which points do they violate the terms exactly (line numbers) ?

**Comment by Sharrisii** [comment]
Ok.
@deu : perhaps consider this (setting the official branding to "off" all the time and perhaps renaming the gentoo package to "newmoon" instead (rather than palemoon) ?
Considering what tobin said, and spockman02's reference to the openbsd palemoon issue (which seems to be this: https://github.com/jasperla/openbsd-wip/issues/86 ) and revolved around simply adding non-standard configuration options (which is similar in deu's palemoon ebuild), the official branding option is probably going to be contested, at least if uploaded to gentoo packages.
Also, could you add a license on the palemoon-overlay repo ? This is going to have to be done anyway for reference purposes when you upload the palemoon or newmoon package to gentoo.

**Comment by mattatobin** [comment]
Nice try. Deu is a good guy on the side of light.

**Comment by Sharrisii** [comment]
@wolfbeast I wasn't trying to do that, and will definitely adhere to not using official branding 
(see earlier post: "In TAZ, palemoon is build with official branding= off".)

What I wanted to say is that deu could also eliminate the official branding option and set it to "off" all the time, so that both of us are in full compliance with the palemoon terms.
The benefit for me then is that it will ensure that a (unbranded) palemoon package will indeed appear on gentoo packages, so that next versions of TAZ could include the browser without requiring too much manual labour.

**Comment by mattatobin** [comment]
@deu is an official Pale Moon packager for gentoo. He works with us to produce a proper overlay with official configuration. He is not here to service your alternative build configurations.

You need not recommend anything to him nor advise him on compliance with the redist agreement. He is well aware of it and has worked very hard to produce a configuration to service gentoo users wishing to use Pale Moon not some inferior build with or without the name.

**Comment by Sharrisii** [comment]
@mattatobin Ok, no problem. I didn't mean any disrespect.

**Comment by johnny-mac** [comment]
Wow, mattatobin you should really learn how to be respectful. Very condescending. We probably wouldn't be stuck with this stupid CoC if not for people like you.

**Comment by mattatobin** [comment]
Wow, @johnny-mac you should really learn how to not necro-post on issues you have no business posting in. Very irrelevant. We probably wouldn't get stupid notifications three months later that have no value if not for people like you.
